kind: Secret
apiVersion: v1
metadata:
  name: capstone-secret
  namespace: capstone
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: user # base 64 encoded for root
  MYSQL_DATABASE: wordpress
  MYSQL_USER: user
  MYSQL_PASSWORD: user # base 64 encoded for user
  WORDPRESS_DB_USER: user
  WORDPRESS_DB_PASSWORD: user # base 64 encoded for user
