kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: configmap-volume
          mountPath: /etc/nginx/conf.d
          readOnly: true
      env:
        - name: db-password
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
      volumeMounts:
        - name: secret-volumemount
          mountPath: /etc/db-credentials
          readOnly: true

  volumes:
    - name: configmap-volume
      configMap:
        name: app-config
  volumes:
    - name: secret-volumemount
      secret:
        secretName: db-credentials

